### ISSUE TITLE
Leaked intentReceiver

### ISSUE THREAD

**Issue by ThomasBS** [omorandi/TiAndroidSMS#9]
Hi Olivier,
first of all, thank you for this module. It was exactly what I needed. I'm kinda new to android/titanium development, so I dont know if the problem is on my side or your code. When sending an SMS using your module, pressing back button on the emulator gives this error:

```
[ERROR] :  ActivityThread: Activity org.appcelerator.titanium.TiActivity has leaked IntentReceiver ti.android.sms.SmsModule$2@414e6b30 that was originally registered here. Are you missing a call to unregisterReceiver()?
[ERROR] :  ActivityThread: android.app.IntentReceiverLeaked: Activity org.appcelerator.titanium.TiActivity has leaked IntentReceiver ti.android.sms.SmsModule$2@414e6b30 that was originally registered here. Are you missing a call to unregisterReceiver()?
[ERROR] :  ActivityThread:  at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:792)
[ERROR] :  ActivityThread:  at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:593)
[ERROR] :  ActivityThread:  at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1111)
[ERROR] :  ActivityThread:  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1098)
[ERROR] :  ActivityThread:  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1092)
[ERROR] :  ActivityThread:  at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:365)
[ERROR] :  ActivityThread:  at ti.android.sms.SmsModule.setupIntentReceivers(SmsModule.java:118)
[ERROR] :  ActivityThread:  at ti.android.sms.SmsModule.<init>(SmsModule.java:56)
[ERROR] :  ActivityThread:  at java.lang.Class.newInstanceImpl(Native Method)
[ERROR] :  ActivityThread:  at java.lang.Class.newInstance(Class.java:1319)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.KrollProxy.createProxy(KrollProxy.java:139)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[ERROR] :  ActivityThread:  at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[ERROR] :  ActivityThread:  at ti.modules.titanium.ui.TableViewRowProxy.handleMessage(TableViewRowProxy.java:186)
[ERROR] :  ActivityThread:  at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  ActivityThread:  at android.os.Looper.loop(Looper.java:137)
[ERROR] :  ActivityThread:  at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
```

Is that to be expected? What am I doing wrong? Any help appreciated!

Thanks,
Thomas.

**Comment by ThomasBS** [comment]
This only happens on the emulator, not when using my android device. Guess it's not that big of an issue then :v:
